# Generated by Django 4.2.7 on 2024-03-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_app', '0002_alter_asset_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('PHONE', 'PHONE'), ('LAPTOP', 'LAPTOP'), ('TABLETS', 'TABLETS'), ('OTHERS', 'OTHERS')], max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='condition',
            field=models.CharField(max_length=50),
        ),
    ]
